[project]
authors = ["Horned_Axe <horned_axe@proton.me>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "A_star"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
streamlit = ">=1.38.0,<2"
matplotlib = ">=3.9.2,<4"
numpy = ">=1.26.4,<2"
